apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: caretta
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://groundcover-com.github.io/caretta
    chart: caretta
    targetRevision: "0.0.18"

  destination:
    server: https://kubernetes.default.svc
    namespace: caretta

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true